# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATLocationManager-MacOSX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ATLocationManager', :path => '../../../'
  # Pods for ATLocationManager-MacOSX

  target 'ATLocationManager-MacOSXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ATLocationManager-MacOSXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
