use_frameworks!

workspace './Example/ATLocationManager.xcworkspace'
project './Example/iOS/ATLocationManagerExample-iOS' do
    target ATLocationManagerExample-iOS do
      pod 'ATLocationManager', :path => './ATLocationManager'
    end
end

project './Example/OSX/ATLocationManagerExample-MacOSX' do
    target ATLocationManager-MacOSX do
      pod 'ATLocationManager', :path => './ATLocationManager'
    end
end
