# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATLocationManagerExample-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ATLocationManager', :path => '../../../'

  # Pods for ATLocationManagerExample-iOS

  target 'ATLocationManagerExample-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ATLocationManagerExample-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
